// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnzkdfwdyprjojoskjcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuemtkZndkeXByam9qb3NramNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTQ0MTAsImV4cCI6MjA2MzczMDQxMH0.Xtv2aqLpaclC1w5gtS5eJgBLvJsoiidvxKh8-JSM9Hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);